blog_src/blog/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_post$', add_post, name='add-post'),
    url(r'^view_post/(?P<post_id>\d+)$', view_post, name='view-post'),
    url(r'^delete_post/(?P<post_id>\d+)$',delete_post, name='delete-post'),
    url(r'^update_post/(?P<post_id>\d+)$',update_post, name='update-post'),
    url(r'^delete_comment/(?P<comment_id>\d+)$',delete_comment, name='delete-comment'),
    url(r'^view_post/$',delete_comment, name='redirect'),
]

blog_src/blog_src/__pycache__/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('blog.urls', 'blog'), namespace='blog'))
]

blog_src/blog_src/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('blog.urls', 'blog'), namespace='blog'))
]

blog_src/blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title       = models.CharField(max_length=200, verbose_name='Event Title')
    create_date = models.DateTimeField(auto_now=True)
    update_date = models.DateTimeField(auto_now=True)
    content     = models.TextField()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['create_date']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

blog_src/blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model   = Post
        fields  = "__all__"

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')

blog_src/blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .models import Post, Comment
from .forms import PostForm, CommentForm

# Create your views here.
def index(request):
	template    = 'list.html'
	posts       = Post.objects.all()

	context = {
		'posts':posts,
	}

	return render(request, template, context)

def add_post(request):
	template    = 'add_post.html'

	if request.method == "POST":
		form = PostForm(request.POST, initial={'author':'admin'})
		if form.is_valid():
			form.save()
		return HttpResponseRedirect(reverse_lazy('blog:index'))
	else:
		context = {
			'post_form':PostForm(),
		}

		return render(request, template, context)

def view_post(request, post_id):
	template    = 'view_post.html'

	post = Post.objects.get(id=int(post_id))
	comments = post.comments.all()
	new_comment = None

	if request.method == 'POST':
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.post = post
			new_comment.save()
	else:
		comment_form = CommentForm()

	context = {
		'post':post,
		'comments':comments,
		'new_comment':new_comment,
		'comment_form':comment_form
	}

	return render(request, template, context)

def delete_post(request,post_id):

	post=Post.objects.get(id=int(post_id))
	post.delete()
	return HttpResponseRedirect(reverse_lazy('blog:index'))

def delete_comment(request,comment_id):
	comment=Comment.objects.get(id=int(comment_id))
	post=comment.post_id
	comment.delete()
	url=reverse_lazy('blog:redirect') + str(post)
	return HttpResponseRedirect(url)

def update_post(request,post_id):
		template="update_post.html"
		post=Post.objects.get(id=int(post_id))

		if request.method == "POST":
			form = PostForm(request.POST, instance=post)
			if form.is_valid():
				form.save()
			return HttpResponseRedirect(reverse_lazy('blog:index'))
		else:
			context = {
				'post_form':PostForm(),
			}

			return render(request, template, context)

blog_src/templates/add_post.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Blog - Add Post</h1>
		<form role="form" action="" method="POST">
		    {% csrf_token %}
			<table class="table table-bordered table-striped">
				<tbody>
					<tr>
						<th>Title</th>
						<th>{{ post_form.title }}</th>
					</tr>
					<tr>
						<th>Content</th>
						<th>{{ post_form.content }}</th>
					</tr>
				</tbody>
			</table>
			<button type="submit" class="btn btn-success">Save</button>
			<a href="{% url 'blog:index' %}" class="btn btn-primary">Back to MAIN</a>
		</form>
	</body>
</html>

blog_src/templates/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>PYTHON not PHYTON</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #000000;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                {# <a class="navbar-brand" href="{% url 'home' %}">Comeback Heroes</a> #}
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
        {% block content %}
        {% endblock content %}
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Copyright &copy; Group 8 - est. 2019</p>
        </footer>
    </body>
</html>

blog_src/templates/list.html
{% extends "base.html" %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Python Blog </h3>
                    <p class="text-light"> "hisssssssssss" - Python &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in posts %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.create_date }} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'blog:view-post' post.id  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock%}

blog_src/templates/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
    <div class="card-body">
        <p class="card-text">Have a new content to publish?</p>
        <a href="{% url 'blog:add-post' %}"
           class="btn btn-danger">Add post!</a>
    </div>
</div>
</div>

{% endblock sidebar %}

blog_src/templates/sidebar_home.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header"></h5>
    <div class="card-body">
        <p class="card-text"></p>
        <a href="{% url 'blog:index' %}"
           class="btn btn-info">Back to MAIN</a>
         <br><br>
        <a href="{% url 'blog:delete-post' post.id %}"
           class="btn btn-danger">Delete Post</a>
         <br><br>
        <a href="{% url 'blog:update-post' post.id %}"
           class="btn btn-primary">Update Post</a>
    </div>
</div>
</div>

{% endblock sidebar %}

blog_src/templates/update_post.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>Python Blog - Update Post</h1>
		<form role="form" action="" method="POST">
		    {% csrf_token %}
			<table class="table table-bordered table-striped">
				<tbody>
					<tr>
						<th>Title</th>
						<th>{{ post_form.title }}</th>
					</tr>
					<tr>
						<th>Content</th>
						<th>{{ post_form.content }}</th>
					</tr>
				</tbody>
			</table>
			<button type="submit" class="btn btn-success">Update</button>
			<a href="{% url 'blog:index' %}" class="btn btn-primary">Back to MAIN</a>
		</form>
	</body>
</html>

blog_src/templates/view_post.html
{% extends 'base.html' %} {% block content %}
<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Python Blog </h3>
                    <p class="text-light">"hisssssssssss" - Python &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.create_date }}</p>
        <p class="card-text ">{{ post.content|linebreaks }}</p>
      </div>
    </div>
    {% block sidebar_home %} {% include 'sidebar_home.html' %} {% endblock sidebar_home %}

    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>{{ comments.count }} comments</h2>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.create_date }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        <a href="{% url 'blog:delete-comment' comment.id  %}" class="btn btn-danger">Delete Comment</a>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Comment posted!
        </div>

        <h3>Leave another comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
          <a href="{% url 'blog:view-post' post.id  %}" class="btn btn-danger btn-lg">Cancel</a>
        </form>

        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}